### ISSUE TITLE
Edge transports out of sync

### ISSUE THREAD

**Issue by ILLISIS** [Danielv123/gridworld#27] opened 2024-03-22 13:36 UTC
After instance crash edge transports that were created after the save are missing.

**Comment by Danielv123** [comment] 2024-03-22 13:56
Edges are created on instance start https://github.com/Danielv123/gridworld/blob/fc62c75300716ad6c1cfd58e4af18ef9668e28c7/instance.js#L118

What do you mean edges that were created after the save? All edges are always created after the save, since the save is created before startup.

Gridworld will overwrite manually created edges on every instance start, so if you created any manually then they will be gone yes

How do you verify that the edges are gone? By them not working in game, by them not appearing in game when using the debug overlay or by them not being present under edge_transports.internal in the instance configuration?

**Comment by ILLISIS** [comment] 2024-03-22 14:11
The edges were not there after it crashed and I rejoined.
Due to the factions bug and some how brute forcing my way past that by switching forces with editor which I cannot replicate now I am no longer able to create edges to test further.

**Comment by ILLISIS** [comment] 2024-03-22 14:18
Found the reason why I couldn't create edge belts.. the instance was not created yet as I hadn't stepped on the edge.

So:
1) created edge to the left isntance
2) moved to the left instance
3) created an edge to the right instance
4) moved to the right instance
<all ok>
5) triggered a crash via the gui click "wooden box" button faction issue
6) started the instance manually
7) joined the right instance from game menu (reconnect)
<edges that were created are not there any more>

after..
joined the left instance via the edge
edge belts are still there.

furthermore
restarting the right side server did not rectify the issue

**Comment by Danielv123** [comment] 2024-03-24 21:22
> joined the left instance via the edge
> edge belts are still there.

I don't understand, what is the bug here? Everything seems to be working like it should.

**Comment by ILLISIS** [comment] 2024-03-24 23:00
Oops sorry.

I mean the edge belts are not there on the right instance after an instance crash which is generally expected as when you place an entity in a normal game and factorio crashes, the last save will not have the entity.

i.e any edges that exist on other instances are not recreated on the instance that crashed after restarting.

hopefully that clarifies.

**Comment by Danielv123** [comment] 2024-03-24 23:19
I need more information. How do you verify is created/is missing? The correct way to check is to enable the edge transports debug view and see if the line is there or not.On 22 Mar 2024 14:36, ILLISIS ***@***.***> wrote:
After instance crash edge transports that were created after the save are missing.

**Comment by Danielv123** [comment] 2024-04-14 20:20
I am closing this issue for now as I need more information to understand what the problem is. If you manage to reproduce again please either reopen this one or open a new issue

**Closed as not planned by Danielv123** 2024-04-14 20:20 UTC
